import React from 'react'

import styles from"./past.module.css"
export default function Past() {
  return (
    <div id={styles.past}>
      <div className={styles.arrange} >

        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-gdsc-nit-andhra-solution-challenge-intro-session/" className={styles.pastevents} id="1"> <img src="../../images/solutionch.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>FEB 3, 2023</div>  <div className={styles.about}>Info Session</div> <div className={styles.desc}>GDSC NIT ANDHRA Solution Challenge Intro Session <br /> National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-tech-talk-with-aditya-c-cloud-computing/" className={styles.pastevents} id="2"> <img src="../../images/speaker.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>JAN 24, 2023</div> <div className={styles.about}>Speaker Session</div> <div className={styles.desc}>Tech Talk with Aditya C. | Cloud Computing <br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-winter-school-with-nikhil-malankar/" className={styles.pastevents} id="3"> <img src="../../images/speaker.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 30, 2022</div> <div className={styles.about}>Speaker Session</div> <div className={styles.desc}>Winter School with Nikhil Malankar <br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-winter-school-session-with-shruthi-pg/" className={styles.pastevents} id="4"> <img src="../../images/winterschool.jpg" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 27, 2022</div> <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Winter School Session with Shruti P.G. <br />National Institute of Technology - Andhra Pradesh</div></a>
      </div>
      <div className={styles.arrange}>

        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-winter-school-session-with-faiz/" className={styles.pastevents} id="5"> <img src="../../images/winterschool.jpg" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 24, 2022</div> <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Winter School Session with Faiz <br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-winter-school-dsa-session-1/" className={styles.pastevents} id="6"> <img src="../../images/winterschool.jpg" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 23, 2022</div> <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Winter School DSA Session-1 <br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-winter-school-web-dev-course-session-1/" className={styles.pastevents} id="7"> <img src="../../images/winterschool.jpg" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 22, 2022</div> <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Winter School Web Dev Course Session-1 <br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-gdsc-nit-andhra-winter-school/" className={styles.pastevents} id="8"> <img src="../../images/studyjam.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>DEC 21, 2022</div> <div className={styles.about}>Study Jam Workshop</div> <div className={styles.desc}>GDSC NIT Andhra Winter School <br />National Institute of Technology - Andhra Pradesh</div></a>
      </div>
      <div className={styles.arrange}>

        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-webinar-with-soundarya-balasubramani/" className={styles.pastevents} id="9"> <img src="../../images/speaker.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>NOV 23, 2022</div> <div className={styles.about}>Speaker Session</div> <div className={styles.desc}>Webinar with Soundarya Balasubramani<br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-data-structures-and-algorithms-demo-session/" className={styles.pastevents} id="10"><img src="../../images/demoday.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>NOV 11, 2022</div> <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Data Structures and Algorithms Demo Session<br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-web-development-demo-session/" className={styles.pastevents} id="11"><img src="../../images/demoday.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>NOV 10,2022</div>  <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Web Development Demo Session<br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-git-and-github-demo-session/" className={styles.pastevents} id="12"><img src="../../images/demoday.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>NOV 9, 2022</div>  <div className={styles.about}>Demo Day</div> <div className={styles.desc}>Git and GitHub Demo Session<br />National Institute of Technology - Andhra Pradesh</div></a>
      </div>
      <div className={styles.arrange}>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-roadmap/" className={styles.pastevents} id="13"><img src="../../images/speaker.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>OCT 31, 2022</div> <div className={styles.about}>Speaker Session</div> <div className={styles.desc}>Roadmap<br />National Institute of Technology - Andhra Pradesh</div></a>
        <a href="https://gdsc.community.dev/events/details/developer-student-clubs-national-institute-of-technologynit-andhra-pradesh-presents-info-session/" className={styles.pastevents} id="14"><img src="../../images/infosession.png" alt="" srcset="" style={{borderRadius:"100%",width:"5vw",height:"5vw"}}/> <div className={styles.date}>SEP 12, 2022</div> <div className={styles.about}>Info Session</div><div className={styles.desc}>Info Session<br />National Institute of Technology - Andhra Pradesh</div></a>
      </div>


    </div>
  )
} 